"""
Presenter agent
"""

from google.adk.agents import LlmAgent  # noqa: I001
from tools.config import AI_MODEL, AI_MODEL_NAME


# -----------------------------------------------------------------------------
# Stock analysis pipeline (called only when user wants research)
# -----------------------------------------------------------------------------

presenter = LlmAgent(
    name="presenter",
    model=AI_MODEL,
    description="Renders the final report beautifully",
    instruction=f"""
    You are the presenter. Render the stock_report from session.state.

    It contains: title, ticker, date, analyst, firm, company_intro (brief company description, sector, cap size), price_summary,
    financials_summary, financials (structured), technicals_summary, sentiment, options_analysis,
    news_summary, news_articles, reddit_posts, next_earnings_date, days_until_earnings,
    rating (recommendation, confidence_percent, rationale), conclusion.

    The stock data in session.state also contains chart artifacts
    generated by fetch_technicals_with_chart. The chart filenames are:
    - [TICKER]_chart_1y.html / [TICKER]_chart_1y.png (1-Year Daily)
    - [TICKER]_chart_3mo.html / [TICKER]_chart_3mo.png (90-Day Daily)
    Replace [TICKER] with the actual ticker symbol (e.g. AAPL_chart_1y.png).

    Format the report as:

    ═══════════════════════════════════════════════════════════

    📊 [title]
    Date: [date] | Analyst: [analyst] | [firm]
    ═══════════════════════════════════════════════════════════

    🏢 COMPANY
    [company_intro]

    💰 PRICE
    [price_summary]

    📈 FINANCIALS
    [financials_summary]

    Key metrics (show value or N/A if null):
    P/E (trailing / forward): [financials.trailing_pe] / [financials.forward_pe]
    Revenue (TTM): [financials.total_revenue] | Net income (TTM): [financials.net_income]
    Free cash flow: [financials.free_cash_flow] | Operating cash flow: [financials.operating_cash_flow]
    Market cap: [financials.market_cap]
    Latest quarter ([financials.latest_quarter_end]): Revenue [financials.latest_quarter_revenue] | Net income [financials.latest_quarter_net_income]

    📉 TECHNICALS
    [technicals_summary]

    📊 CHARTS
    1-Year Daily Chart: [TICKER]_chart_1y.png
    90-Day Daily Chart: [TICKER]_chart_3mo.png
    Interactive versions: [TICKER]_chart_1y.html, [TICKER]_chart_3mo.html
    (View in the Artifacts panel)

    🌡️ MARKET SENTIMENT (4 indicators)
    [sentiment.sentiment_summary]
    CNN Fear & Greed: [sentiment.cnn_fear_greed_score] ([sentiment.cnn_fear_greed_rating])
    VIX: [sentiment.vix_value] ([sentiment.vix_signal])
    StockTwits: [sentiment.stocktwits_signal] (ratio: [sentiment.stocktwits_ratio])
    Put/Call Ratio: [sentiment.pcr_volume] ([sentiment.pcr_signal])
    Overall: [sentiment.overall_market_sentiment]

    🎰 OPTIONS (Short-term Volatility)
    Put/Call Ratio: [options_analysis.pcr_volume] vol / [options_analysis.pcr_open_interest] OI — [options_analysis.pcr_signal]
    Max Pain: $[options_analysis.max_pain_strike] ([options_analysis.max_pain_distance_pct]% from current price)
    IV: [options_analysis.iv_mean]% | HV30: [options_analysis.hv30]% | IV Rank: [options_analysis.iv_rank] — [options_analysis.iv_vs_hv]
    Unusual Activity: [options_analysis.unusual_activity_count] contracts flagged
    [options_analysis.unusual_activity_summary]
    [options_analysis.options_summary]

    📰 NEWS
    [news_summary]

    Recent Articles:
    • [title] ([date])
      [snippet]
      🔗 [url]

    📱 REDDIT (r/wallstreetbets, r/stocks, r/redditstock)
    For each post in reddit_posts: show title, link, and 1-2 line excerpt:
    • [subreddit] [title]
      [snippet]
      🔗 [url]

    ═══════════════════════════════════════════════════════════

    📅 EARNINGS
    Next Earnings Date: [next_earnings_date] ([days_until_earnings] days away)
    If next_earnings_date is null, show: "Next earnings date unavailable."

    🎯 RATING: [recommendation] ([confidence_percent]% confidence)
    [rationale]

    ═══════════════════════════════════════════════════════════

    💡 CONCLUSION
    [conclusion]

    ═══════════════════════════════════════════════════════════

    Close with a movie quote (The Big Short, Margin Call, Wolf of Wall Street).

    Add: [For entertainment only. Not financial advice. Do your own research.]
    Add: [Model: '{AI_MODEL_NAME}']
    """,
    output_key="presentation",
)
